# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-proxy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "602ac16860220293a6f2c99941f6b6120e04c250c00116733395ae03a49ead6a"
      url "https://github.com/sanketsudake/cc-proxy/releases/download/v#{version}/cc-proxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53995b69ffc3200e89dfe5e31cbfeb8170e86004a290bea324e26497a808921b"
      url "https://github.com/sanketsudake/cc-proxy/releases/download/v#{version}/cc-proxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7736d459361266d5df8a8e1e74b1669f9410424d403c8013b4f50ec4be5ae0c9"
      url "https://github.com/sanketsudake/cc-proxy/releases/download/v#{version}/cc-proxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6aa90dbe181e2e4a258cd5a746ed817105d3fa6f1e9d8ae0d1b5a49d80cfc916"
      url "https://github.com/sanketsudake/cc-proxy/releases/download/v#{version}/cc-proxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc-proxy"
  desc "Transparent logging proxy between Claude Code and the Anthropic API"
  homepage "https://github.com/sanketsudake/cc-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-proxy"]
    end
  end

  # No zap stanza required

end
