# This file was generated by GoReleaser. DO NOT EDIT.
cask "chrome-cdp" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "feda9317e3510054aea2c88a690c50c4ab3356af2ed43da8ece127440ebeb326"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "554c7b2061dfba60a039b3e0773838fe41098404590131d80128f2f93286aa8e"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "906818aa3730727e4404242dee9bba5846f7e1281001189ac3238677e662ac9e"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cf10e14e1210bb3823fb29e40f5f29aa03e15b66693908fcfc1c40d787a9ec2"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chrome-cdp"
  desc "Drive your already-running local Chrome from the command line over CDP"
  homepage "https://github.com/sanketsudake/chrome-cdp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chrome-cdp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chrome-cdp"]
    end
  end

  # No zap stanza required

end
