# This file was generated by GoReleaser. DO NOT EDIT.
cask "chrome-cdp" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "234325da88aea6db8e6934806c09ee5dbc90196e388d639b1bdaf83a8ad4b358"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09f0ea61d60500ba29db3407bce3f54ea3b70bbb79c05cde76a893e9a8c65bc4"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46732463ff95730da1f535334a820237b988dd402a07b81d55eeb67125b9fca2"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb91de1efc13226d4a2e1b1752c458afc7ff6ca4e5f11327ccb91de5ac9deb73"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chrome-cdp"
  desc "Drive your already-running local Chrome from the command line over CDP"
  homepage "https://github.com/sanketsudake/chrome-cdp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chrome-cdp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chrome-cdp"]
    end
  end

  # No zap stanza required

end
