# This file was generated by GoReleaser. DO NOT EDIT.
cask "chrome-cdp" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "697cd8fcb29ca2f790d547a05531b5bc4081f2d6b3de1b75befaead9c0a1f85a"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b525806463918799dce7b1d02d805774ba858b27ed7bb8bb4895269e8325594"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ea9789763ed59617bd5d737edb8de1bb1a9f3103584eac7576cb00ce6f99e2e"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b20d840d87e0bc97f6ffa48668a6a2360e69e349e0af53015c40cbfb3d4d24af"
      url "https://github.com/sanketsudake/chrome-cdp-cli/releases/download/v#{version}/chrome-cdp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chrome-cdp"
  desc "Drive your already-running local Chrome from the command line over CDP"
  homepage "https://github.com/sanketsudake/chrome-cdp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chrome-cdp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chrome-cdp"]
    end
  end

  # No zap stanza required

end
