# This file was generated by GoReleaser. DO NOT EDIT.
cask "portless" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "17738b827658f9a7b27eadafb3c4e26d2f957bf18e436360cea207d370272442"
      url "https://github.com/sanketsudake/go-portless/releases/download/v#{version}/portless_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d09b876302a57515da65555519a90c13776c1f75a9f8c6ec0f403731a93431ee"
      url "https://github.com/sanketsudake/go-portless/releases/download/v#{version}/portless_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a7a7273463c6aff7a8d5b691569bfb156c11f6ad68ede56f8476aa89f36fe99"
      url "https://github.com/sanketsudake/go-portless/releases/download/v#{version}/portless_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c247c661b19f1e703bf3ecbb9d8a7a33862f3e5c23e6eafa8399efbd433c1a5"
      url "https://github.com/sanketsudake/go-portless/releases/download/v#{version}/portless_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portless"
  desc "Dial services by name with readiness built into the dial — the portless CLI"
  homepage "https://github.com/sanketsudake/go-portless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portless"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portless"]
    end
  end

  # No zap stanza required

end
